# Quality gates. Lint, tests and screenshots run in the pinned CI image only.

ci_image := env("CI_IMAGE", "printed-labels-maker-ci:local")
ci_platform := "linux/amd64"

# Image used by `just ci-lock` to resolve the Python closure (same Python minor as the CI image: 3.11)
lock_image := "python:3.11-slim-bookworm@sha256:b1add8a6f2aca6bcfcf0b9c9b522352f7ce0d62a3d556a2f2f32511aa0cca250"

# Build (or pull) the CI image
ci-image:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -n "${CI_IMAGE:-}" ]; then docker pull --quiet --platform {{ci_platform}} "$CI_IMAGE" >/dev/null
    else docker build --quiet --platform {{ci_platform}} --build-context repo=. -t {{ci_image}} \
      -f test/ci/Dockerfile test >/dev/null; fi

# Regenerate test/ci/requirements.lock after any requirements change
ci-lock:
    #!/usr/bin/env bash
    set -euo pipefail
    lock="$(docker run --rm --platform {{ci_platform}} -v "$PWD/test":/test:ro {{lock_image}} sh -c \
      'pip install --quiet --root-user-action=ignore -r /test/ci/requirements.txt >&2 \
       && pip freeze --all --exclude pip --exclude setuptools --exclude wheel')"
    { echo "# Generated by just ci-lock: do not edit."; echo "$lock"; } > test/ci/requirements.lock

# Lint: every checker, nothing modified
lint: ci-image
    just _in-ci test/ci/lint.sh

# Format: apply the formatters
fmt: ci-image
    just _in-ci test/ci/lint.sh fix

# Full pipeline of one app (tests + goldens)
test APP: ci-image
    just _in-ci "test/$(just _test-dir '{{APP}}')/run-tests.sh"

# Regenerate the goldens of one app / of every app (commit them when the UI change is intended)
site-gui-goldens: (_gui-goldens "site")
all-gui-goldens: site-gui-goldens

# Fail if test/screenshot (or test/screenshot/<APP>) differs from HEAD
check-goldens APP="":
    test/ci/check-goldens.sh {{APP}}

# Determinism proof: regenerate RUNS times and compare the bytes
gui-goldens-stability APP RUNS="3": ci-image
    just _in-ci test/ci/goldens-stability.sh "$(just _test-dir '{{APP}}')" {{RUNS}}

# Exactly what CI runs, same image, same order (goldens are compared with HEAD: commit first)
ci: ci-image
    just _in-ci test/ci/lint.sh
    just _in-ci test/site/run-tests.sh tests
    just _in-ci test/site/run-tests.sh goldens
    test/ci/check-goldens.sh

# Cloudflare (wrangler.jsonc). Native on the host, the exception the playbook allows for builds and deploys:
# the pinned wrangler of package-lock.json is installed in node_modules/ first.

# Local server with the production routing and site/_headers (wrangler dev)
dev:
    npm ci --no-audit --no-fund
    npx wrangler dev

# Production deploys come from Cloudflare Workers Builds on every push to main. This recipe is the fallback:
# it refuses to run off main, with local changes, or when HEAD is not origin/main (commits CI never saw).
# Manual deploy, fallback of Workers Builds (wrangler deploy)
deploy:
    #!/usr/bin/env bash
    set -euo pipefail
    branch="$(git rev-parse --abbrev-ref HEAD)"
    if [ "$branch" != main ]; then echo "just deploy: only from main (current branch: $branch)" >&2; exit 1; fi
    if [ -n "$(git status --porcelain --untracked-files=all)" ]; then
      echo "just deploy: the worktree is not clean, commit or stash first" >&2; git status --short >&2; exit 1
    fi
    git fetch --quiet origin main
    if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/main)" ]; then
      echo "just deploy: HEAD is not origin/main, deploy only what was pushed and passed CI" >&2; exit 1
    fi
    npm ci --no-audit --no-fund
    npx wrangler deploy

_gui-goldens DIR: ci-image
    just _in-ci test/{{DIR}}/run-tests.sh goldens

# Run in the CI image, repo on /repo, as the host user (files never become root-owned on Linux hosts)
_in-ci +CMD:
    docker run --rm --init --platform {{ci_platform}} --user "$(id -u):$(id -g)" -e HOME=/tmp \
      -v "$PWD":/repo -w /repo {{ci_image}} {{CMD}}

# App name -> test folder; exit 2 on an unknown app
_test-dir APP:
    #!/usr/bin/env bash
    case "{{APP}}" in
      site/|site) echo "site" ;;
      *) echo "Unknown app: {{APP}}" >&2; exit 2 ;;
    esac
